- name: Change user shell to zsh
  user: name={{ user }} 
    state=present shell=/usr/bin/zsh

- name: Register Oh My Zsh installation status
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  become: false

- name: Install Oh My Zsh
  shell: git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  when: not oh_my_zsh.stat.exists
  become: false

- name: Update Oh My Zsh
  shell: git -C ~/.oh-my-zsh pull
  when: oh_my_zsh.isdir is not defined
  become: false
